### PR TITLE
Remove javascript-brunch, as it is deprecated

### PR DESCRIPTION
**Pull request by aladh**

### CODE REVIEW

**Comment by shvaikalesh** [comment]
LGTM

**Comment by paulmillr** [comment]
31d514b

**Comment by aladh** [comment]
@paulmillr Sorry, I don't understand what's wrong with this PR. Could you please explain why it can't be merged? I checked out the commit you linked, but I'm not sure what you meant by referencing it.

Thanks

**Comment by shvaikalesh** [comment]
I believe incorrect commit was linked. https://github.com/brunch/with-react/commit/9e3b095f01bf1138c761c1af8878efe58be232cf

**Pull request closed without merging**
